// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class CentralKitchenKhaiVpm
{
    public int CentralKitchenKhaiVpmid { get; set; }

    public string KitchenName { get; set; }

    public string Address { get; set; }

    public int? Capacity { get; set; }

    public DateOnly? OpenDate { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public decimal? MonthlyCost { get; set; }

    public bool? IsActive { get; set; }

    public int KitchenTypeKhaiVpmid { get; set; }

    public virtual ICollection<FranchiseStorePhucBhv> FranchiseStorePhucBhvs { get; set; } = new List<FranchiseStorePhucBhv>();

    public virtual ICollection<InventoryHuyNd> InventoryHuyNds { get; set; } = new List<InventoryHuyNd>();

    public virtual KitchenTypeKhaiVpm KitchenTypeKhaiVpm { get; set; }
}