// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class DeliveryHuyNv
{
    public int DeliveryHuyNvid { get; set; }

    public string DeliveryCode { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public decimal? DeliveryCost { get; set; }

    public string Address { get; set; }

    public int? Status { get; set; }

    public int? EstimatedTime { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsActive { get; set; }

    public int OrderLamNqid { get; set; }

    public int DeliveryMethodHuyNvid { get; set; }

    public virtual DeliveryMethodHuyNv DeliveryMethodHuyNv { get; set; }

    public virtual OrderHeaderLamNq OrderLamNq { get; set; }
}