// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class FranchiseStorePhucBhv
{
    public int FranchiseStorePhucBhvid { get; set; }

    public string StoreName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateOnly? OpeningDate { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public decimal? Revenue { get; set; }

    public bool? IsActive { get; set; }

    public int StoreRegionPhucBhvid { get; set; }

    public int CentralKitchenKhaiVpmid { get; set; }

    public virtual CentralKitchenKhaiVpm CentralKitchenKhaiVpm { get; set; }

    public virtual ICollection<OrderHeaderLamNq> OrderHeaderLamNqs { get; set; } = new List<OrderHeaderLamNq>();

    public virtual StoreRegionPhucBhv StoreRegionPhucBhv { get; set; }
}