// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class InventoryLocationHuyNd
{
    public int InventoryLocationHuyNdid { get; set; }

    public string LocationName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<InventoryHuyNd> InventoryHuyNds { get; set; } = new List<InventoryHuyNd>();
}