// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class InventoryHuyNd
{
    public int InventoryHuyNdid { get; set; }

    public string ItemName { get; set; }

    public int? Quantity { get; set; }

    public string Unit { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string BatchNumber { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public decimal? Cost { get; set; }

    public bool? IsActive { get; set; }

    public int CentralKitchenKhaiVpmid { get; set; }

    public int InventoryLocationHuyNdid { get; set; }

    public virtual CentralKitchenKhaiVpm CentralKitchenKhaiVpm { get; set; }

    public virtual InventoryLocationHuyNd InventoryLocationHuyNd { get; set; }
}