// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class KitchenTypeKhaiVpm
{
    public int KitchenTypeKhaiVpmid { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CentralKitchenKhaiVpm> CentralKitchenKhaiVpms { get; set; } = new List<CentralKitchenKhaiVpm>();
}