// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class OrderHeaderLamNq
{
    public int OrderLamNqid { get; set; }

    public string OrderCode { get; set; }

    public DateOnly? OrderDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Tax { get; set; }

    public decimal? FinalAmount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool? IsActive { get; set; }

    public int FranchiseStorePhucBhvid { get; set; }

    public int ProductKietDtid { get; set; }

    public int OrderStatusLamNqid { get; set; }

    public virtual DeliveryHuyNv DeliveryHuyNv { get; set; }

    public virtual FranchiseStorePhucBhv FranchiseStorePhucBhv { get; set; }

    public virtual OrderStatusLamNq OrderStatusLamNq { get; set; }

    public virtual ProductKietDt ProductKietDt { get; set; }
}