// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class ProductVariantHauPt
{
    public int ProductVariantHauPtid { get; set; }

    public string VariantName { get; set; }

    public decimal? Price { get; set; }

    public string Sku { get; set; }

    public int? StockQuantity { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public int? Status { get; set; }

    public DateOnly? PublishDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsActive { get; set; }

    public int ProductKietDtid { get; set; }

    public int VariantColorHauPtid { get; set; }

    public virtual ProductKietDt ProductKietDt { get; set; }

    public virtual VariantColorHauPt VariantColorHauPt { get; set; }
}