// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class ProductCategoryKietDt
{
    public int ProductCategoryKietDtid { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<ProductKietDt> ProductKietDts { get; set; } = new List<ProductKietDt>();
}