// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class ProductKietDt
{
    public int ProductKietDtid { get; set; }

    public string ProductName { get; set; }

    public string Sku { get; set; }

    public decimal? Price { get; set; }

    public string Unit { get; set; }

    public string Description { get; set; }

    public string WarrantyInfo { get; set; }

    public int? Status { get; set; }

    public DateOnly? PublishDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }

    public int ProductCategoryKietDtid { get; set; }

    public int VehicleModelLamTtid { get; set; }

    public virtual ICollection<OrderHeaderLamNq> OrderHeaderLamNqs { get; set; } = new List<OrderHeaderLamNq>();

    public virtual ProductCategoryKietDt ProductCategoryKietDt { get; set; }

    public virtual ICollection<ProductVariantHauPt> ProductVariantHauPts { get; set; } = new List<ProductVariantHauPt>();

    public virtual VehicleModelLamTt VehicleModelLamTt { get; set; }
}