// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class StoreRegionPhucBhv
{
    public int StoreRegionPhucBhvid { get; set; }

    public string RegionName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<FranchiseStorePhucBhv> FranchiseStorePhucBhvs { get; set; } = new List<FranchiseStorePhucBhv>();
}