// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class VariantColorHauPt
{
    public int VariantColorHauPtid { get; set; }

    public string ColorName { get; set; }

    public string ColorCode { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<ProductVariantHauPt> ProductVariantHauPts { get; set; } = new List<ProductVariantHauPt>();
}