// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class VehicleBrandLamTt
{
    public int VehicleBrandLamTtid { get; set; }

    public string BrandName { get; set; }

    public string Country { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<VehicleModelLamTt> VehicleModelLamTts { get; set; } = new List<VehicleModelLamTt>();
}