// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cKitchen.Entities.HuyND.Models;

public partial class VehicleModelLamTt
{
    public int VehicleModelLamTtid { get; set; }

    public string ModelName { get; set; }

    public string Description { get; set; }

    public string EngineType { get; set; }

    public int? ReleaseYear { get; set; }

    public int? Status { get; set; }

    public DateOnly? PublishDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool? IsActive { get; set; }

    public int VehicleBrandLamTtid { get; set; }

    public virtual ICollection<ProductKietDt> ProductKietDts { get; set; } = new List<ProductKietDt>();

    public virtual VehicleBrandLamTt VehicleBrandLamTt { get; set; }
}