// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using cKitchen.Entities.HuyND.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace cKitchen.Repositories.HuyND.DBContext;

public partial class CentralKitchenFranchiseDBContext : DbContext
{
    public CentralKitchenFranchiseDBContext()
    {
    }

    public CentralKitchenFranchiseDBContext(DbContextOptions<CentralKitchenFranchiseDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CentralKitchenKhaiVpm> CentralKitchenKhaiVpms { get; set; }

    public virtual DbSet<DeliveryHuyNv> DeliveryHuyNvs { get; set; }

    public virtual DbSet<DeliveryMethodHuyNv> DeliveryMethodHuyNvs { get; set; }

    public virtual DbSet<FranchiseStorePhucBhv> FranchiseStorePhucBhvs { get; set; }

    public virtual DbSet<InventoryHuyNd> InventoryHuyNds { get; set; }

    public virtual DbSet<InventoryLocationHuyNd> InventoryLocationHuyNds { get; set; }

    public virtual DbSet<KitchenTypeKhaiVpm> KitchenTypeKhaiVpms { get; set; }

    public virtual DbSet<OrderHeaderLamNq> OrderHeaderLamNqs { get; set; }

    public virtual DbSet<OrderStatusLamNq> OrderStatusLamNqs { get; set; }

    public virtual DbSet<ProductCategoryKietDt> ProductCategoryKietDts { get; set; }

    public virtual DbSet<ProductKietDt> ProductKietDts { get; set; }

    public virtual DbSet<ProductVariantHauPt> ProductVariantHauPts { get; set; }

    public virtual DbSet<StoreRegionPhucBhv> StoreRegionPhucBhvs { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<VariantColorHauPt> VariantColorHauPts { get; set; }

    public virtual DbSet<VehicleBrandLamTt> VehicleBrandLamTts { get; set; }

    public virtual DbSet<VehicleModelLamTt> VehicleModelLamTts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=IMHYYYY\\SQLEXPRESS;Initial Catalog=CentralKitchenFranchiseDB;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CentralKitchenKhaiVpm>(entity =>
        {
            entity.HasKey(e => e.CentralKitchenKhaiVpmid).HasName("PK__CentralK__599E4217A92FC9D5");

            entity.ToTable("CentralKitchenKhaiVPM");

            entity.Property(e => e.CentralKitchenKhaiVpmid).HasColumnName("CentralKitchenKhaiVPMId");
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.KitchenName).HasMaxLength(250);
            entity.Property(e => e.KitchenTypeKhaiVpmid).HasColumnName("KitchenTypeKhaiVPMId");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.MonthlyCost).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.KitchenTypeKhaiVpm).WithMany(p => p.CentralKitchenKhaiVpms)
                .HasForeignKey(d => d.KitchenTypeKhaiVpmid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CentralKi__Kitch__38996AB5");
        });

        modelBuilder.Entity<DeliveryHuyNv>(entity =>
        {
            entity.HasKey(e => e.DeliveryHuyNvid).HasName("PK__Delivery__616FBFF2603EBBBA");

            entity.ToTable("DeliveryHuyNV");

            entity.HasIndex(e => e.OrderLamNqid, "UQ__Delivery__4629ACE21C148483").IsUnique();

            entity.Property(e => e.DeliveryHuyNvid).HasColumnName("DeliveryHuyNVId");
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeliveryCode).HasMaxLength(100);
            entity.Property(e => e.DeliveryCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DeliveryMethodHuyNvid).HasColumnName("DeliveryMethodHuyNVId");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.OrderLamNqid).HasColumnName("OrderLamNQId");

            entity.HasOne(d => d.DeliveryMethodHuyNv).WithMany(p => p.DeliveryHuyNvs)
                .HasForeignKey(d => d.DeliveryMethodHuyNvid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeliveryHuyNV_DeliveryMethod");

            entity.HasOne(d => d.OrderLamNq).WithOne(p => p.DeliveryHuyNv)
                .HasForeignKey<DeliveryHuyNv>(d => d.OrderLamNqid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeliveryHuyNV_OrderHeader");
        });

        modelBuilder.Entity<DeliveryMethodHuyNv>(entity =>
        {
            entity.HasKey(e => e.DeliveryMethodHuyNvid).HasName("PK__Delivery__F1641D4AE453D800");

            entity.ToTable("DeliveryMethodHuyNV");

            entity.Property(e => e.DeliveryMethodHuyNvid).HasColumnName("DeliveryMethodHuyNVId");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MethodName)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<FranchiseStorePhucBhv>(entity =>
        {
            entity.HasKey(e => e.FranchiseStorePhucBhvid).HasName("PK__Franchis__982DD2BAA57ACBE0");

            entity.ToTable("FranchiseStorePhucBHV");

            entity.Property(e => e.FranchiseStorePhucBhvid).HasColumnName("FranchiseStorePhucBHVId");
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.CentralKitchenKhaiVpmid).HasColumnName("CentralKitchenKhaiVPMId");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.Revenue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.StoreName).HasMaxLength(250);
            entity.Property(e => e.StoreRegionPhucBhvid).HasColumnName("StoreRegionPhucBHVId");

            entity.HasOne(d => d.CentralKitchenKhaiVpm).WithMany(p => p.FranchiseStorePhucBhvs)
                .HasForeignKey(d => d.CentralKitchenKhaiVpmid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Franchise__Centr__3E52440B");

            entity.HasOne(d => d.StoreRegionPhucBhv).WithMany(p => p.FranchiseStorePhucBhvs)
                .HasForeignKey(d => d.StoreRegionPhucBhvid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Franchise__Store__3D5E1FD2");
        });

        modelBuilder.Entity<InventoryHuyNd>(entity =>
        {
            entity.HasKey(e => e.InventoryHuyNdid).HasName("PK__Inventor__FDA7156C6ABAF80D");

            entity.ToTable("InventoryHuyND");

            entity.Property(e => e.InventoryHuyNdid).HasColumnName("InventoryHuyNDId");
            entity.Property(e => e.BatchNumber).HasMaxLength(100);
            entity.Property(e => e.CentralKitchenKhaiVpmid).HasColumnName("CentralKitchenKhaiVPMId");
            entity.Property(e => e.Cost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.InventoryLocationHuyNdid).HasColumnName("InventoryLocationHuyNDId");
            entity.Property(e => e.ItemName).HasMaxLength(250);
            entity.Property(e => e.Unit).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.CentralKitchenKhaiVpm).WithMany(p => p.InventoryHuyNds)
                .HasForeignKey(d => d.CentralKitchenKhaiVpmid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventory__Centr__4316F928");

            entity.HasOne(d => d.InventoryLocationHuyNd).WithMany(p => p.InventoryHuyNds)
                .HasForeignKey(d => d.InventoryLocationHuyNdid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventory__Inven__440B1D61");
        });

        modelBuilder.Entity<InventoryLocationHuyNd>(entity =>
        {
            entity.HasKey(e => e.InventoryLocationHuyNdid).HasName("PK__Inventor__3DD35D94EA16F01E");

            entity.ToTable("InventoryLocationHuyND");

            entity.Property(e => e.InventoryLocationHuyNdid).HasColumnName("InventoryLocationHuyNDId");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.LocationName).HasMaxLength(150);
        });

        modelBuilder.Entity<KitchenTypeKhaiVpm>(entity =>
        {
            entity.HasKey(e => e.KitchenTypeKhaiVpmid).HasName("PK__KitchenT__16B7FC191FE18A59");

            entity.ToTable("KitchenTypeKhaiVPM");

            entity.Property(e => e.KitchenTypeKhaiVpmid).HasColumnName("KitchenTypeKhaiVPMId");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.TypeName).HasMaxLength(150);
        });

        modelBuilder.Entity<OrderHeaderLamNq>(entity =>
        {
            entity.HasKey(e => e.OrderLamNqid).HasName("PK__OrderHea__4629ACE3605F628B");

            entity.ToTable("OrderHeaderLamNQ");

            entity.Property(e => e.OrderLamNqid).HasColumnName("OrderLamNQId");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FinalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FranchiseStorePhucBhvid).HasColumnName("FranchiseStorePhucBHVId");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.OrderCode).HasMaxLength(100);
            entity.Property(e => e.OrderStatusLamNqid).HasColumnName("OrderStatusLamNQId");
            entity.Property(e => e.ProductKietDtid).HasColumnName("ProductKietDTId");
            entity.Property(e => e.Tax).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.FranchiseStorePhucBhv).WithMany(p => p.OrderHeaderLamNqs)
                .HasForeignKey(d => d.FranchiseStorePhucBhvid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderHead__Franc__48CFD27E");

            entity.HasOne(d => d.OrderStatusLamNq).WithMany(p => p.OrderHeaderLamNqs)
                .HasForeignKey(d => d.OrderStatusLamNqid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderHead__Order__4AB81AF0");

            entity.HasOne(d => d.ProductKietDt).WithMany(p => p.OrderHeaderLamNqs)
                .HasForeignKey(d => d.ProductKietDtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderHead__Produ__49C3F6B7");
        });

        modelBuilder.Entity<OrderStatusLamNq>(entity =>
        {
            entity.HasKey(e => e.OrderStatusLamNqid).HasName("PK__OrderSta__7059C2A9D9378F63");

            entity.ToTable("OrderStatusLamNQ");

            entity.Property(e => e.OrderStatusLamNqid).HasColumnName("OrderStatusLamNQId");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.StatusName).HasMaxLength(100);
        });

        modelBuilder.Entity<ProductCategoryKietDt>(entity =>
        {
            entity.HasKey(e => e.ProductCategoryKietDtid).HasName("PK__ProductC__E713CC459BF03E60");

            entity.ToTable("ProductCategoryKietDT");

            entity.Property(e => e.ProductCategoryKietDtid).HasColumnName("ProductCategoryKietDTId");
            entity.Property(e => e.CategoryName).HasMaxLength(150);
            entity.Property(e => e.Description).HasMaxLength(500);
        });

        modelBuilder.Entity<ProductKietDt>(entity =>
        {
            entity.HasKey(e => e.ProductKietDtid).HasName("PK__ProductK__F00675BF3DB1A4CD");

            entity.ToTable("ProductKietDT");

            entity.Property(e => e.ProductKietDtid).HasColumnName("ProductKietDTId");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductCategoryKietDtid).HasColumnName("ProductCategoryKietDTId");
            entity.Property(e => e.ProductName).HasMaxLength(250);
            entity.Property(e => e.Sku)
                .HasMaxLength(100)
                .HasColumnName("SKU");
            entity.Property(e => e.Unit).HasMaxLength(50);
            entity.Property(e => e.VehicleModelLamTtid).HasColumnName("VehicleModelLamTTId");
            entity.Property(e => e.WarrantyInfo).HasMaxLength(500);

            entity.HasOne(d => d.ProductCategoryKietDt).WithMany(p => p.ProductKietDts)
                .HasForeignKey(d => d.ProductCategoryKietDtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductKi__Produ__2D27B809");

            entity.HasOne(d => d.VehicleModelLamTt).WithMany(p => p.ProductKietDts)
                .HasForeignKey(d => d.VehicleModelLamTtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductKi__Vehic__2E1BDC42");
        });

        modelBuilder.Entity<ProductVariantHauPt>(entity =>
        {
            entity.HasKey(e => e.ProductVariantHauPtid).HasName("PK__ProductV__5B357E1672BFB6A8");

            entity.ToTable("ProductVariantHauPT");

            entity.Property(e => e.ProductVariantHauPtid).HasColumnName("ProductVariantHauPTId");
            entity.Property(e => e.ImageUrl).HasMaxLength(1000);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductKietDtid).HasColumnName("ProductKietDTId");
            entity.Property(e => e.Sku)
                .HasMaxLength(100)
                .HasColumnName("SKU");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.VariantColorHauPtid).HasColumnName("VariantColorHauPTId");
            entity.Property(e => e.VariantName).HasMaxLength(150);

            entity.HasOne(d => d.ProductKietDt).WithMany(p => p.ProductVariantHauPts)
                .HasForeignKey(d => d.ProductKietDtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductVa__Produ__32E0915F");

            entity.HasOne(d => d.VariantColorHauPt).WithMany(p => p.ProductVariantHauPts)
                .HasForeignKey(d => d.VariantColorHauPtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductVa__Varia__33D4B598");
        });

        modelBuilder.Entity<StoreRegionPhucBhv>(entity =>
        {
            entity.HasKey(e => e.StoreRegionPhucBhvid).HasName("PK__StoreReg__84BAC62CC1AB07C7");

            entity.ToTable("StoreRegionPhucBHV");

            entity.Property(e => e.StoreRegionPhucBhvid).HasColumnName("StoreRegionPhucBHVId");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.RegionName).HasMaxLength(150);
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<VariantColorHauPt>(entity =>
        {
            entity.HasKey(e => e.VariantColorHauPtid).HasName("PK__VariantC__FE1F00BDF53AB796");

            entity.ToTable("VariantColorHauPT");

            entity.Property(e => e.VariantColorHauPtid).HasColumnName("VariantColorHauPTId");
            entity.Property(e => e.ColorCode).HasMaxLength(20);
            entity.Property(e => e.ColorName).HasMaxLength(100);
        });

        modelBuilder.Entity<VehicleBrandLamTt>(entity =>
        {
            entity.HasKey(e => e.VehicleBrandLamTtid).HasName("PK__VehicleB__650BA39E9ED5E66D");

            entity.ToTable("VehicleBrandLamTT");

            entity.Property(e => e.VehicleBrandLamTtid).HasColumnName("VehicleBrandLamTTId");
            entity.Property(e => e.BrandName).HasMaxLength(150);
            entity.Property(e => e.Country).HasMaxLength(100);
        });

        modelBuilder.Entity<VehicleModelLamTt>(entity =>
        {
            entity.HasKey(e => e.VehicleModelLamTtid).HasName("PK__VehicleM__C2E792B8B9757E74");

            entity.ToTable("VehicleModelLamTT");

            entity.Property(e => e.VehicleModelLamTtid).HasColumnName("VehicleModelLamTTId");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.EngineType).HasMaxLength(100);
            entity.Property(e => e.ModelName).HasMaxLength(150);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.VehicleBrandLamTtid).HasColumnName("VehicleBrandLamTTId");

            entity.HasOne(d => d.VehicleBrandLamTt).WithMany(p => p.VehicleModelLamTts)
                .HasForeignKey(d => d.VehicleBrandLamTtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VehicleMo__Vehic__286302EC");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}